default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: 12345
  

development:
  <<: *default
  database: task_manager_development

test:
  <<: *default
  database: task_manager_test

production:
  <<: *default
  database: task_manager_production